<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

function project_tease() { ?>
	<div class="details-tab">
	<?php if (rwmb_meta('mak_location') != '') {
	?>
	<span class="project-location"><?php echo rwmb_meta('mak_location');?></span>
	<?php } ?>
	<a href="#" class="next">Scroll Down</a>
	</div>
<?php }
	
function big_bg_image(){
	if ( has_post_thumbnail() ){
		global $post;
		$image = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), 'bg' );
		echo '<div class="bg-wrapper" style="background-image: url(' . $image[0] . ')">';
		echo '</div>';
	}
}

function entry_content_open() {
	echo '<div class="project-content wrap">';
}

function entry_content_close() {
	if (rwmb_meta('mak_desc') != '') {
		echo '<p class="short-desc">' . rwmb_meta('mak_desc') . '</p>';
	}
	echo '</div>';
}

remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );
remove_action( 'genesis_entry_content', 'genesis_do_post_content' );
remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_open', 5 );
remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_close', 15 );
remove_action( 'genesis_entry_footer', 'genesis_post_meta' );

add_action( 'genesis_after_content', 'project_tease' );
add_action( 'genesis_after_content', 'big_bg_image' );

add_action( 'genesis_before_footer', 'entry_content_open', 1 );
add_action( 'genesis_before_footer', 'genesis_do_post_content', 2 );
add_action( 'genesis_before_footer', 'entry_content_close', 3 );

//* This file handles pages, but only exists for the sake of child theme forward compatibility.
genesis();
